/*
  SOLARIUM - Script de TRIGGERS + PROCEDIMIENTOS ALMACENADOS
  Para los 4 módulos (CH, P, C, J) y la bitácora compartida.

  Base objetivo: DB_TiendaBelleza (ajusta si tu BD tiene otro nombre).
  Motor: Microsoft SQL Server.

  Nota:
  - Los triggers registran INSERT/UPDATE/DELETE en BITACORA_OPERACIONES.
  - ACTOR_ID_USUARIO queda NULL (desde triggers no hay contexto del usuario app).
  - Se crean SPs para CRUD y listados con paginación simple.
*/

USE [DB_TiendaBelleza];
GO

/* =========================
   BITÁCORA (compartido)
========================= */
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'BITACORA_OPERACIONES')
BEGIN
  CREATE TABLE BITACORA_OPERACIONES (
    ID_BITACORA       INT IDENTITY(1,1) PRIMARY KEY,
    OPERACION         VARCHAR(10) NOT NULL,  -- INSERT | UPDATE | DELETE
    TABLA             VARCHAR(100) NOT NULL,
    ID_REGISTRO       INT NULL,
    DESCRIPCION       VARCHAR(255) NULL,
    ACTOR_ID_USUARIO  INT NULL,
    FECHA             DATETIME NOT NULL DEFAULT(GETDATE())
  );
END
GO

/* =========================
   HELPERS: drop trigger if exists
========================= */
DECLARE @sql NVARCHAR(MAX);

/* =========================
   TRIGGERS (bitácora)
   Tablas: CATEGORIAS, SERVICIOS, CLIENTES, ROLES, USUARIOS, RESERVAS, TRABAJOS, PAGOS
========================= */

/* ---- CATEGORIAS ---- */
IF OBJECT_ID('dbo.TR_CATEGORIAS_AIUD_BITACORA', 'TR') IS NOT NULL
  DROP TRIGGER dbo.TR_CATEGORIAS_AIUD_BITACORA;
GO
CREATE TRIGGER dbo.TR_CATEGORIAS_AIUD_BITACORA
ON dbo.CATEGORIAS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRY
    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'UPDATE', 'CATEGORIAS', d.ID_CATEGORIA, 'Actualización en CATEGORIAS', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END

    IF EXISTS (SELECT 1 FROM inserted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'INSERT', 'CATEGORIAS', i.ID_CATEGORIA, 'Inserción en CATEGORIAS', NULL, GETDATE()
      FROM inserted i;
      RETURN;
    END

    IF EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'DELETE', 'CATEGORIAS', d.ID_CATEGORIA, 'Eliminación/Desactivación en CATEGORIAS', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
  END TRY
  BEGIN CATCH
    -- No bloquear operación por bitácora
  END CATCH
END
GO

/* ---- SERVICIOS ---- */
IF OBJECT_ID('dbo.TR_SERVICIOS_AIUD_BITACORA', 'TR') IS NOT NULL
  DROP TRIGGER dbo.TR_SERVICIOS_AIUD_BITACORA;
GO
CREATE TRIGGER dbo.TR_SERVICIOS_AIUD_BITACORA
ON dbo.SERVICIOS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRY
    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'UPDATE', 'SERVICIOS', d.ID_SERVICIO, 'Actualización en SERVICIOS', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END

    IF EXISTS (SELECT 1 FROM inserted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'INSERT', 'SERVICIOS', i.ID_SERVICIO, 'Inserción en SERVICIOS', NULL, GETDATE()
      FROM inserted i;
      RETURN;
    END

    IF EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'DELETE', 'SERVICIOS', d.ID_SERVICIO, 'Eliminación/Desactivación en SERVICIOS', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
  END TRY
  BEGIN CATCH
  END CATCH
END
GO

/* ---- CLIENTES ---- */
IF OBJECT_ID('dbo.TR_CLIENTES_AIUD_BITACORA', 'TR') IS NOT NULL
  DROP TRIGGER dbo.TR_CLIENTES_AIUD_BITACORA;
GO
CREATE TRIGGER dbo.TR_CLIENTES_AIUD_BITACORA
ON dbo.CLIENTES
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRY
    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'UPDATE', 'CLIENTES', d.ID_CLIENTE, 'Actualización en CLIENTES', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM inserted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'INSERT', 'CLIENTES', i.ID_CLIENTE, 'Inserción en CLIENTES', NULL, GETDATE()
      FROM inserted i;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'DELETE', 'CLIENTES', d.ID_CLIENTE, 'Eliminación/Desactivación en CLIENTES', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
  END TRY
  BEGIN CATCH
  END CATCH
END
GO

/* ---- ROLES ---- */
IF OBJECT_ID('dbo.TR_ROLES_AIUD_BITACORA', 'TR') IS NOT NULL
  DROP TRIGGER dbo.TR_ROLES_AIUD_BITACORA;
GO
CREATE TRIGGER dbo.TR_ROLES_AIUD_BITACORA
ON dbo.ROLES
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRY
    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'UPDATE', 'ROLES', d.ID_ROL, 'Actualización en ROLES', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM inserted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'INSERT', 'ROLES', i.ID_ROL, 'Inserción en ROLES', NULL, GETDATE()
      FROM inserted i;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'DELETE', 'ROLES', d.ID_ROL, 'Eliminación/Desactivación en ROLES', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
  END TRY
  BEGIN CATCH
  END CATCH
END
GO

/* ---- USUARIOS ---- */
IF OBJECT_ID('dbo.TR_USUARIOS_AIUD_BITACORA', 'TR') IS NOT NULL
  DROP TRIGGER dbo.TR_USUARIOS_AIUD_BITACORA;
GO
CREATE TRIGGER dbo.TR_USUARIOS_AIUD_BITACORA
ON dbo.USUARIOS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRY
    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'UPDATE', 'USUARIOS', d.ID_USUARIO, 'Actualización en USUARIOS', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM inserted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'INSERT', 'USUARIOS', i.ID_USUARIO, 'Inserción en USUARIOS', NULL, GETDATE()
      FROM inserted i;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'DELETE', 'USUARIOS', d.ID_USUARIO, 'Eliminación/Desactivación en USUARIOS', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
  END TRY
  BEGIN CATCH
  END CATCH
END
GO

/* ---- RESERVAS ---- */
IF OBJECT_ID('dbo.TR_RESERVAS_AIUD_BITACORA', 'TR') IS NOT NULL
  DROP TRIGGER dbo.TR_RESERVAS_AIUD_BITACORA;
GO
CREATE TRIGGER dbo.TR_RESERVAS_AIUD_BITACORA
ON dbo.RESERVAS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRY
    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'UPDATE', 'RESERVAS', d.ID_RESERVA, 'Actualización en RESERVAS', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM inserted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'INSERT', 'RESERVAS', i.ID_RESERVA, 'Inserción en RESERVAS', NULL, GETDATE()
      FROM inserted i;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT 'DELETE', 'RESERVAS', d.ID_RESERVA, 'Eliminación en RESERVAS', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
  END TRY
  BEGIN CATCH
  END CATCH
END
GO

/* ---- TRABAJOS (si existe) ---- */
IF OBJECT_ID('dbo.TR_TRABAJOS_AIUD_BITACORA', 'TR') IS NOT NULL
  DROP TRIGGER dbo.TR_TRABAJOS_AIUD_BITACORA;
GO
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TRABAJOS')
EXEC('
CREATE TRIGGER dbo.TR_TRABAJOS_AIUD_BITACORA
ON dbo.TRABAJOS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRY
    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT ''UPDATE'', ''TRABAJOS'', d.ID_TRABAJO, ''Actualización en TRABAJOS'', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM inserted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT ''INSERT'', ''TRABAJOS'', i.ID_TRABAJO, ''Inserción en TRABAJOS'', NULL, GETDATE()
      FROM inserted i;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT ''DELETE'', ''TRABAJOS'', d.ID_TRABAJO, ''Eliminación en TRABAJOS'', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
  END TRY
  BEGIN CATCH
  END CATCH
END
');
GO

/* ---- PAGOS (si existe) ---- */
IF OBJECT_ID('dbo.TR_PAGOS_AIUD_BITACORA', 'TR') IS NOT NULL
  DROP TRIGGER dbo.TR_PAGOS_AIUD_BITACORA;
GO
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PAGOS')
EXEC('
CREATE TRIGGER dbo.TR_PAGOS_AIUD_BITACORA
ON dbo.PAGOS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRY
    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT ''UPDATE'', ''PAGOS'', d.ID_PAGO, ''Actualización en PAGOS'', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM inserted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT ''INSERT'', ''PAGOS'', i.ID_PAGO, ''Inserción en PAGOS'', NULL, GETDATE()
      FROM inserted i;
      RETURN;
    END
    IF EXISTS (SELECT 1 FROM deleted)
    BEGIN
      INSERT INTO BITACORA_OPERACIONES (OPERACION, TABLA, ID_REGISTRO, DESCRIPCION, ACTOR_ID_USUARIO, FECHA)
      SELECT ''DELETE'', ''PAGOS'', d.ID_PAGO, ''Eliminación en PAGOS'', NULL, GETDATE()
      FROM deleted d;
      RETURN;
    END
  END TRY
  BEGIN CATCH
  END CATCH
END
');
GO

/* =========================
   PROCEDIMIENTOS ALMACENADOS
========================= */

/* ========= MÓDULO CH - CATEGORÍAS ========= */
IF OBJECT_ID('dbo.sp_Categorias_Listar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Categorias_Listar;
GO
CREATE PROCEDURE dbo.sp_Categorias_Listar
  @Page INT = 1,
  @PageSize INT = 10
AS
BEGIN
  SET NOCOUNT ON;
  DECLARE @Offset INT = (@Page - 1) * @PageSize;

  SELECT COUNT(1) AS total FROM CATEGORIAS;

  SELECT ID_CATEGORIA AS id_categoria, NOMBRE AS nombre, DESCRIPCION AS descripcion, ESTADO AS estado
  FROM CATEGORIAS
  ORDER BY NOMBRE
  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY;
END
GO

IF OBJECT_ID('dbo.sp_Categorias_Crear', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Categorias_Crear;
GO
CREATE PROCEDURE dbo.sp_Categorias_Crear
  @Nombre VARCHAR(100),
  @Descripcion VARCHAR(255) = NULL
AS
BEGIN
  SET NOCOUNT ON;
  INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION, ESTADO)
  VALUES (@Nombre, @Descripcion, 'ACTIVO');
  SELECT SCOPE_IDENTITY() AS id_categoria;
END
GO

IF OBJECT_ID('dbo.sp_Categorias_Editar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Categorias_Editar;
GO
CREATE PROCEDURE dbo.sp_Categorias_Editar
  @IdCategoria INT,
  @Nombre VARCHAR(100),
  @Descripcion VARCHAR(255) = NULL,
  @Estado VARCHAR(10) = 'ACTIVO'
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE CATEGORIAS
  SET NOMBRE = @Nombre,
      DESCRIPCION = @Descripcion,
      ESTADO = @Estado
  WHERE ID_CATEGORIA = @IdCategoria;

  SELECT @@ROWCOUNT AS rows_affected;
END
GO

IF OBJECT_ID('dbo.sp_Categorias_Desactivar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Categorias_Desactivar;
GO
CREATE PROCEDURE dbo.sp_Categorias_Desactivar
  @IdCategoria INT
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE CATEGORIAS SET ESTADO = 'INACTIVO' WHERE ID_CATEGORIA = @IdCategoria;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

/* ========= MÓDULO CH - SERVICIOS ========= */
IF OBJECT_ID('dbo.sp_Servicios_Listar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Servicios_Listar;
GO
CREATE PROCEDURE dbo.sp_Servicios_Listar
  @IdCategoria INT = NULL,
  @Page INT = 1,
  @PageSize INT = 10
AS
BEGIN
  SET NOCOUNT ON;
  DECLARE @Offset INT = (@Page - 1) * @PageSize;

  SELECT COUNT(1) AS total
  FROM SERVICIOS
  WHERE (@IdCategoria IS NULL OR ID_CATEGORIA = @IdCategoria);

  SELECT
    s.ID_SERVICIO AS id_servicio,
    s.ID_CATEGORIA AS id_categoria,
    s.NOMBRE AS nombre,
    s.DESCRIPCION AS descripcion,
    s.PRECIO AS precio,
    s.DURACION_MINUTOS AS duracion_minutos,
    c.NOMBRE AS categoria,
    s.ESTADO AS estado
  FROM SERVICIOS s
  JOIN CATEGORIAS c ON s.ID_CATEGORIA = c.ID_CATEGORIA
  WHERE (@IdCategoria IS NULL OR s.ID_CATEGORIA = @IdCategoria)
  ORDER BY s.NOMBRE
  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY;
END
GO

IF OBJECT_ID('dbo.sp_Servicios_Crear', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Servicios_Crear;
GO
CREATE PROCEDURE dbo.sp_Servicios_Crear
  @IdCategoria INT,
  @Nombre VARCHAR(100),
  @Descripcion VARCHAR(255) = NULL,
  @Precio DECIMAL(10,2),
  @DuracionMinutos INT = NULL
AS
BEGIN
  SET NOCOUNT ON;
  INSERT INTO SERVICIOS (ID_CATEGORIA, NOMBRE, DESCRIPCION, PRECIO, DURACION_MINUTOS, ESTADO)
  VALUES (@IdCategoria, @Nombre, @Descripcion, @Precio, @DuracionMinutos, 'ACTIVO');
  SELECT SCOPE_IDENTITY() AS id_servicio;
END
GO

IF OBJECT_ID('dbo.sp_Servicios_Editar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Servicios_Editar;
GO
CREATE PROCEDURE dbo.sp_Servicios_Editar
  @IdServicio INT,
  @IdCategoria INT,
  @Nombre VARCHAR(100),
  @Descripcion VARCHAR(255) = NULL,
  @Precio DECIMAL(10,2),
  @DuracionMinutos INT = NULL,
  @Estado VARCHAR(10) = 'ACTIVO'
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE SERVICIOS
  SET ID_CATEGORIA = @IdCategoria,
      NOMBRE = @Nombre,
      DESCRIPCION = @Descripcion,
      PRECIO = @Precio,
      DURACION_MINUTOS = @DuracionMinutos,
      ESTADO = @Estado
  WHERE ID_SERVICIO = @IdServicio;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

IF OBJECT_ID('dbo.sp_Servicios_Desactivar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Servicios_Desactivar;
GO
CREATE PROCEDURE dbo.sp_Servicios_Desactivar
  @IdServicio INT
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE SERVICIOS SET ESTADO = 'INACTIVO' WHERE ID_SERVICIO = @IdServicio;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

/* ========= MÓDULO P - CLIENTES ========= */
IF OBJECT_ID('dbo.sp_Clientes_ListarBuscar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Clientes_ListarBuscar;
GO
CREATE PROCEDURE dbo.sp_Clientes_ListarBuscar
  @Q VARCHAR(200) = NULL,
  @Page INT = 1,
  @PageSize INT = 10
AS
BEGIN
  SET NOCOUNT ON;
  DECLARE @Offset INT = (@Page - 1) * @PageSize;

  SELECT COUNT(1) AS total
  FROM CLIENTES
  WHERE (@Q IS NULL OR NOMBRE LIKE @Q OR APELLIDO LIKE @Q);

  SELECT ID_CLIENTE AS id_cliente, NOMBRE AS nombre, APELLIDO AS apellido, TELEFONO AS telefono, CORREO AS correo
  FROM CLIENTES
  WHERE (@Q IS NULL OR NOMBRE LIKE @Q OR APELLIDO LIKE @Q)
  ORDER BY NOMBRE
  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY;
END
GO

IF OBJECT_ID('dbo.sp_Clientes_Crear', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Clientes_Crear;
GO
CREATE PROCEDURE dbo.sp_Clientes_Crear
  @Nombre VARCHAR(100),
  @Apellido VARCHAR(100),
  @Telefono VARCHAR(20) = NULL,
  @Correo VARCHAR(100) = NULL
AS
BEGIN
  SET NOCOUNT ON;
  INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, CORREO)
  VALUES (@Nombre, @Apellido, @Telefono, @Correo);
  SELECT SCOPE_IDENTITY() AS id_cliente;
END
GO

IF OBJECT_ID('dbo.sp_Clientes_Editar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Clientes_Editar;
GO
CREATE PROCEDURE dbo.sp_Clientes_Editar
  @IdCliente INT,
  @Nombre VARCHAR(100),
  @Apellido VARCHAR(100),
  @Telefono VARCHAR(20) = NULL,
  @Correo VARCHAR(100) = NULL
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE CLIENTES
  SET NOMBRE = @Nombre, APELLIDO = @Apellido, TELEFONO = @Telefono, CORREO = @Correo
  WHERE ID_CLIENTE = @IdCliente;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

IF OBJECT_ID('dbo.sp_Clientes_Eliminar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Clientes_Eliminar;
GO
CREATE PROCEDURE dbo.sp_Clientes_Eliminar
  @IdCliente INT
AS
BEGIN
  SET NOCOUNT ON;
  DELETE FROM CLIENTES WHERE ID_CLIENTE = @IdCliente;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

IF OBJECT_ID('dbo.sp_Clientes_Historial', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Clientes_Historial;
GO
CREATE PROCEDURE dbo.sp_Clientes_Historial
  @IdCliente INT
AS
BEGIN
  SET NOCOUNT ON;
  SELECT
    r.ID_RESERVA AS id_reserva,
    CONVERT(VARCHAR, r.FECHA_RESERVA, 23) AS fecha_reserva,
    CONVERT(VARCHAR, r.HORA_RESERVA, 8) AS hora_reserva,
    r.ESTADO AS estado,
    s.NOMBRE AS servicio,
    u.NOMBRE + '' '' + u.APELLIDO AS usuario
  FROM RESERVAS r
  JOIN SERVICIOS s ON r.ID_SERVICIO = s.ID_SERVICIO
  JOIN USUARIOS u ON r.ID_USUARIO = u.ID_USUARIO
  WHERE r.ID_CLIENTE = @IdCliente
  ORDER BY r.FECHA_RESERVA DESC, r.HORA_RESERVA DESC;
END
GO

/* ========= MÓDULO C - ROLES ========= */
IF OBJECT_ID('dbo.sp_Roles_Listar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Roles_Listar;
GO
CREATE PROCEDURE dbo.sp_Roles_Listar
  @Page INT = 1,
  @PageSize INT = 20
AS
BEGIN
  SET NOCOUNT ON;
  DECLARE @Offset INT = (@Page - 1) * @PageSize;
  SELECT COUNT(1) AS total FROM ROLES;
  SELECT ID_ROL AS id_rol, NOMBRE AS nombre, ESTADO AS estado
  FROM ROLES
  ORDER BY NOMBRE
  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY;
END
GO

IF OBJECT_ID('dbo.sp_Roles_Crear', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Roles_Crear;
GO
CREATE PROCEDURE dbo.sp_Roles_Crear
  @Nombre VARCHAR(50)
AS
BEGIN
  SET NOCOUNT ON;
  INSERT INTO ROLES (NOMBRE, ESTADO) VALUES (UPPER(@Nombre), 'ACTIVO');
  SELECT SCOPE_IDENTITY() AS id_rol;
END
GO

IF OBJECT_ID('dbo.sp_Roles_Editar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Roles_Editar;
GO
CREATE PROCEDURE dbo.sp_Roles_Editar
  @IdRol INT,
  @Nombre VARCHAR(50),
  @Estado VARCHAR(10) = 'ACTIVO'
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE ROLES SET NOMBRE = UPPER(@Nombre), ESTADO = @Estado WHERE ID_ROL = @IdRol;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

IF OBJECT_ID('dbo.sp_Roles_Desactivar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Roles_Desactivar;
GO
CREATE PROCEDURE dbo.sp_Roles_Desactivar
  @IdRol INT
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE ROLES SET ESTADO = 'INACTIVO' WHERE ID_ROL = @IdRol;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

/* ========= MÓDULO C - USUARIOS ========= */
IF OBJECT_ID('dbo.sp_Usuarios_ListarBuscar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Usuarios_ListarBuscar;
GO
CREATE PROCEDURE dbo.sp_Usuarios_ListarBuscar
  @Q VARCHAR(200) = NULL,
  @Page INT = 1,
  @PageSize INT = 10
AS
BEGIN
  SET NOCOUNT ON;
  DECLARE @Offset INT = (@Page - 1) * @PageSize;

  SELECT COUNT(1) AS total
  FROM USUARIOS u
  WHERE (@Q IS NULL OR u.NOMBRE LIKE @Q OR u.APELLIDO LIKE @Q OR u.USUARIO LIKE @Q OR u.CORREO LIKE @Q);

  SELECT
    u.ID_USUARIO AS id_usuario,
    u.NOMBRE AS nombre,
    u.APELLIDO AS apellido,
    u.CORREO AS correo,
    u.USUARIO AS usuario,
    u.ESPECIALIDAD AS especialidad,
    u.ESTADO AS estado,
    r.ID_ROL AS id_rol,
    r.NOMBRE AS rol
  FROM USUARIOS u
  JOIN ROLES r ON u.ID_ROL = r.ID_ROL
  WHERE (@Q IS NULL OR u.NOMBRE LIKE @Q OR u.APELLIDO LIKE @Q OR u.USUARIO LIKE @Q OR u.CORREO LIKE @Q)
  ORDER BY u.NOMBRE
  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY;
END
GO

IF OBJECT_ID('dbo.sp_Usuarios_Crear', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Usuarios_Crear;
GO
CREATE PROCEDURE dbo.sp_Usuarios_Crear
  @Nombre VARCHAR(100),
  @Apellido VARCHAR(100),
  @Correo VARCHAR(100),
  @Usuario VARCHAR(50),
  @PasswordHash VARCHAR(255),
  @Especialidad VARCHAR(100) = NULL,
  @IdRol INT
AS
BEGIN
  SET NOCOUNT ON;
  INSERT INTO USUARIOS (NOMBRE, APELLIDO, CORREO, USUARIO, PASSWORD, ESPECIALIDAD, ID_ROL, ESTADO)
  VALUES (@Nombre, @Apellido, @Correo, @Usuario, @PasswordHash, @Especialidad, @IdRol, 'ACTIVO');
  SELECT SCOPE_IDENTITY() AS id_usuario;
END
GO

IF OBJECT_ID('dbo.sp_Usuarios_Editar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Usuarios_Editar;
GO
CREATE PROCEDURE dbo.sp_Usuarios_Editar
  @IdUsuario INT,
  @Nombre VARCHAR(100),
  @Apellido VARCHAR(100),
  @Correo VARCHAR(100),
  @Usuario VARCHAR(50),
  @Especialidad VARCHAR(100) = NULL
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE USUARIOS
  SET NOMBRE = @Nombre, APELLIDO = @Apellido, CORREO = @Correo, USUARIO = @Usuario, ESPECIALIDAD = @Especialidad
  WHERE ID_USUARIO = @IdUsuario;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

IF OBJECT_ID('dbo.sp_Usuarios_CambiarRol', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Usuarios_CambiarRol;
GO
CREATE PROCEDURE dbo.sp_Usuarios_CambiarRol
  @IdUsuario INT,
  @IdRol INT
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE USUARIOS SET ID_ROL = @IdRol WHERE ID_USUARIO = @IdUsuario;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

IF OBJECT_ID('dbo.sp_Usuarios_Desactivar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Usuarios_Desactivar;
GO
CREATE PROCEDURE dbo.sp_Usuarios_Desactivar
  @IdUsuario INT
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE USUARIOS SET ESTADO = 'INACTIVO' WHERE ID_USUARIO = @IdUsuario;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

/* ========= MÓDULO J - RESERVAS ========= */
IF OBJECT_ID('dbo.sp_Reservas_Crear', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Reservas_Crear;
GO
CREATE PROCEDURE dbo.sp_Reservas_Crear
  @IdCliente INT,
  @IdServicio INT,
  @IdUsuario INT,
  @FechaReserva DATE,
  @HoraReserva VARCHAR(8),
  @Observacion VARCHAR(255) = NULL
AS
BEGIN
  SET NOCOUNT ON;
  INSERT INTO RESERVAS (ID_CLIENTE, ID_SERVICIO, ID_USUARIO, FECHA_RESERVA, HORA_RESERVA, ESTADO, OBSERVACION)
  VALUES (@IdCliente, @IdServicio, @IdUsuario, @FechaReserva, @HoraReserva, 'PENDIENTE', @Observacion);
  SELECT SCOPE_IDENTITY() AS id_reserva;
END
GO

IF OBJECT_ID('dbo.sp_Reservas_ListarPorFecha', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Reservas_ListarPorFecha;
GO
CREATE PROCEDURE dbo.sp_Reservas_ListarPorFecha
  @FechaInicio DATE,
  @FechaFin DATE,
  @Page INT = 1,
  @PageSize INT = 10
AS
BEGIN
  SET NOCOUNT ON;
  DECLARE @Offset INT = (@Page - 1) * @PageSize;

  SELECT COUNT(1) AS total
  FROM RESERVAS
  WHERE FECHA_RESERVA BETWEEN @FechaInicio AND @FechaFin;

  SELECT
    r.ID_RESERVA AS id_reserva,
    c.NOMBRE + ' ' + c.APELLIDO AS cliente,
    s.NOMBRE AS servicio,
    u.NOMBRE + ' ' + u.APELLIDO AS usuario,
    CONVERT(VARCHAR, r.FECHA_RESERVA, 23) AS fecha_reserva,
    CONVERT(VARCHAR, r.HORA_RESERVA, 8) AS hora_reserva,
    r.ESTADO AS estado,
    r.OBSERVACION AS observacion
  FROM RESERVAS r
  JOIN CLIENTES c  ON r.ID_CLIENTE = c.ID_CLIENTE
  JOIN SERVICIOS s ON r.ID_SERVICIO = s.ID_SERVICIO
  JOIN USUARIOS u  ON r.ID_USUARIO = u.ID_USUARIO
  WHERE r.FECHA_RESERVA BETWEEN @FechaInicio AND @FechaFin
  ORDER BY r.FECHA_RESERVA DESC, r.HORA_RESERVA DESC
  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY;
END
GO

IF OBJECT_ID('dbo.sp_Reservas_Cancelar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Reservas_Cancelar;
GO
CREATE PROCEDURE dbo.sp_Reservas_Cancelar
  @IdReserva INT
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE RESERVAS SET ESTADO = 'CANCELADO' WHERE ID_RESERVA = @IdReserva;
  SELECT @@ROWCOUNT AS rows_affected;
END
GO

/* ========= MÓDULO J - TRABAJOS / PAGOS (si existen tablas) ========= */
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TRABAJOS')
BEGIN
  IF OBJECT_ID('dbo.sp_Trabajos_Registrar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Trabajos_Registrar;
  EXEC('
    CREATE PROCEDURE dbo.sp_Trabajos_Registrar
      @IdReserva INT,
      @Estado VARCHAR(20),
      @Notas VARCHAR(255) = NULL
    AS
    BEGIN
      SET NOCOUNT ON;
      INSERT INTO TRABAJOS (ID_RESERVA, ESTADO, NOTAS) VALUES (@IdReserva, @Estado, @Notas);
      SELECT SCOPE_IDENTITY() AS id_trabajo;
    END
  ');
END
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'METODOS_PAGO')
BEGIN
  IF OBJECT_ID('dbo.sp_MetodosPago_Listar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_MetodosPago_Listar;
  EXEC('
    CREATE PROCEDURE dbo.sp_MetodosPago_Listar
    AS
    BEGIN
      SET NOCOUNT ON;
      SELECT ID_METODO_PAGO AS id_metodo_pago, NOMBRE AS nombre
      FROM METODOS_PAGO
      WHERE ESTADO = ''ACTIVO''
      ORDER BY NOMBRE;
    END
  ');
END
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PAGOS')
BEGIN
  IF OBJECT_ID('dbo.sp_Pagos_Registrar', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Pagos_Registrar;
  EXEC('
    CREATE PROCEDURE dbo.sp_Pagos_Registrar
      @IdTrabajo INT,
      @IdMetodoPago INT,
      @Monto DECIMAL(10,2),
      @Estado VARCHAR(20) = ''PAGADO''
    AS
    BEGIN
      SET NOCOUNT ON;
      INSERT INTO PAGOS (ID_TRABAJO, ID_METODO_PAGO, MONTO, ESTADO)
      VALUES (@IdTrabajo, @IdMetodoPago, @Monto, @Estado);
      SELECT SCOPE_IDENTITY() AS id_pago;
    END
  ');
END
GO

/* ========= DASHBOARD BITÁCORA ========= */
IF OBJECT_ID('dbo.sp_Bitacora_KPIs_Hoy', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Bitacora_KPIs_Hoy;
GO
CREATE PROCEDURE dbo.sp_Bitacora_KPIs_Hoy
AS
BEGIN
  SET NOCOUNT ON;
  SELECT
    SUM(CASE WHEN OPERACION = 'INSERT' THEN 1 ELSE 0 END) AS total_insert,
    SUM(CASE WHEN OPERACION = 'UPDATE' THEN 1 ELSE 0 END) AS total_update,
    SUM(CASE WHEN OPERACION = 'DELETE' THEN 1 ELSE 0 END) AS total_delete
  FROM BITACORA_OPERACIONES
  WHERE CAST(FECHA AS DATE) = CAST(GETDATE() AS DATE);
END
GO

IF OBJECT_ID('dbo.sp_Bitacora_Reciente', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Bitacora_Reciente;
GO
CREATE PROCEDURE dbo.sp_Bitacora_Reciente
AS
BEGIN
  SET NOCOUNT ON;
  SELECT TOP 50
    ID_BITACORA AS id_bitacora,
    OPERACION AS operacion,
    TABLA AS tabla,
    ID_REGISTRO AS id_registro,
    DESCRIPCION AS descripcion,
    ACTOR_ID_USUARIO AS actor_id_usuario,
    CONVERT(VARCHAR, FECHA, 120) AS fecha
  FROM BITACORA_OPERACIONES
  ORDER BY FECHA DESC;
END
GO

IF OBJECT_ID('dbo.sp_Bitacora_ActividadPorDia', 'P') IS NOT NULL DROP PROCEDURE dbo.sp_Bitacora_ActividadPorDia;
GO
CREATE PROCEDURE dbo.sp_Bitacora_ActividadPorDia
  @Days INT = 14
AS
BEGIN
  SET NOCOUNT ON;
  SELECT
    CONVERT(VARCHAR, CAST(FECHA AS DATE), 23) AS dia,
    COUNT(1) AS total
  FROM BITACORA_OPERACIONES
  WHERE FECHA >= DATEADD(DAY, -@Days, GETDATE())
  GROUP BY CAST(FECHA AS DATE)
  ORDER BY dia;
END
GO

PRINT '✅ Script aplicado: triggers + procedimientos almacenados.';

