/*
  Script de soporte para módulos CRUD + Bitácora.
  Ejecutar en la instancia donde está la BD (ej. localhost\SQLEXPRESS).

  Nota: NO elimina nada; sólo crea si no existe.
*/

USE [DB_TiendaBelleza];
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'BITACORA_OPERACIONES')
BEGIN
  CREATE TABLE BITACORA_OPERACIONES (
    ID_BITACORA       INT IDENTITY(1,1) PRIMARY KEY,
    OPERACION         VARCHAR(10) NOT NULL,  -- INSERT | UPDATE | DELETE
    TABLA             VARCHAR(100) NOT NULL,
    ID_REGISTRO       INT NULL,
    DESCRIPCION       VARCHAR(255) NULL,
    ACTOR_ID_USUARIO  INT NULL,
    FECHA             DATETIME NOT NULL DEFAULT(GETDATE())
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TRABAJOS')
BEGIN
  CREATE TABLE TRABAJOS (
    ID_TRABAJO    INT IDENTITY(1,1) PRIMARY KEY,
    ID_RESERVA    INT NOT NULL,
    ESTADO        VARCHAR(20) NOT NULL, -- COMPLETADO | INCOMPLETO | ANULADO
    NOTAS         VARCHAR(255) NULL,
    FECHA         DATETIME NOT NULL DEFAULT(GETDATE()),
    CONSTRAINT FK_TRABAJOS_RESERVAS FOREIGN KEY (ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA)
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'METODOS_PAGO')
BEGIN
  CREATE TABLE METODOS_PAGO (
    ID_METODO_PAGO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE         VARCHAR(50) NOT NULL,
    ESTADO         VARCHAR(10) NOT NULL DEFAULT('ACTIVO')
  );

  INSERT INTO METODOS_PAGO (NOMBRE, ESTADO)
  VALUES ('EFECTIVO','ACTIVO'), ('TARJETA','ACTIVO'), ('TRANSFERENCIA','ACTIVO');
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PAGOS')
BEGIN
  CREATE TABLE PAGOS (
    ID_PAGO         INT IDENTITY(1,1) PRIMARY KEY,
    ID_TRABAJO      INT NOT NULL,
    ID_METODO_PAGO  INT NOT NULL,
    MONTO           DECIMAL(10,2) NOT NULL,
    ESTADO          VARCHAR(20) NOT NULL, -- PAGADO | PENDIENTE | ANULADO
    FECHA           DATETIME NOT NULL DEFAULT(GETDATE()),
    CONSTRAINT FK_PAGOS_TRABAJOS FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJOS(ID_TRABAJO),
    CONSTRAINT FK_PAGOS_METODOS FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODOS_PAGO(ID_METODO_PAGO)
  );
END
GO

