USE [DB_TiendaBelleza];
GO

/* ================================================================
   TRIGGERS — escriben en BITACORA con nombres, no IDs
================================================================ */

/* ---- RESPONSABLE: CH — CATEGORIAS ---- */

IF OBJECT_ID('dbo.TR_CATEGORIAS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CATEGORIAS_INSERT;
GO
CREATE TRIGGER dbo.TR_CATEGORIAS_INSERT ON dbo.CATEGORIAS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CATEGORIAS', 'INSERT',
    'Nueva categoría: ' + NOMBRE,
    SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_CATEGORIAS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CATEGORIAS_UPDATE;
GO
CREATE TRIGGER dbo.TR_CATEGORIAS_UPDATE ON dbo.CATEGORIAS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CATEGORIAS', 'UPDATE',
    'Categoría "' + d.NOMBRE + '" → nombre: "' + i.NOMBRE + '" estado: ' + i.ESTADO,
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_CATEGORIA = i.ID_CATEGORIA;
END
GO

IF OBJECT_ID('dbo.TR_CATEGORIAS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CATEGORIAS_DELETE;
GO
CREATE TRIGGER dbo.TR_CATEGORIAS_DELETE ON dbo.CATEGORIAS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CATEGORIAS', 'DELETE',
    'Categoría eliminada: "' + NOMBRE + '"',
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: CH — SERVICIOS ---- */

IF OBJECT_ID('dbo.TR_SERVICIOS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_SERVICIOS_INSERT;
GO
CREATE TRIGGER dbo.TR_SERVICIOS_INSERT ON dbo.SERVICIOS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'SERVICIOS', 'INSERT',
    'Nuevo servicio: "' + i.NOMBRE + '" categoría: "' + ISNULL(c.NOMBRE,'?') + '" precio: Bs.' + CAST(i.PRECIO AS VARCHAR),
    SYSTEM_USER
  FROM inserted i
  LEFT JOIN CATEGORIAS c ON i.ID_CATEGORIA = c.ID_CATEGORIA;
END
GO

IF OBJECT_ID('dbo.TR_SERVICIOS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_SERVICIOS_UPDATE;
GO
CREATE TRIGGER dbo.TR_SERVICIOS_UPDATE ON dbo.SERVICIOS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'SERVICIOS', 'UPDATE',
    'Servicio "' + d.NOMBRE + '" → nombre: "' + i.NOMBRE +
    '" precio: Bs.' + CAST(i.PRECIO AS VARCHAR) + ' estado: ' + i.ESTADO,
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_SERVICIO = i.ID_SERVICIO;
END
GO

IF OBJECT_ID('dbo.TR_SERVICIOS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_SERVICIOS_DELETE;
GO
CREATE TRIGGER dbo.TR_SERVICIOS_DELETE ON dbo.SERVICIOS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'SERVICIOS', 'DELETE',
    'Servicio eliminado: "' + NOMBRE + '" precio: Bs.' + CAST(PRECIO AS VARCHAR),
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: P — CLIENTES ---- */

IF OBJECT_ID('dbo.TR_CLIENTES_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CLIENTES_INSERT;
GO
CREATE TRIGGER dbo.TR_CLIENTES_INSERT ON dbo.CLIENTES AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CLIENTES', 'INSERT',
    'Nuevo cliente: ' + NOMBRE + ' ' + APELLIDO + ' tel: ' + ISNULL(TELEFONO,'—'),
    SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_CLIENTES_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CLIENTES_UPDATE;
GO
CREATE TRIGGER dbo.TR_CLIENTES_UPDATE ON dbo.CLIENTES AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CLIENTES', 'UPDATE',
    'Cliente "' + d.NOMBRE + ' ' + d.APELLIDO +
    '" → nombre: "' + i.NOMBRE + ' ' + i.APELLIDO +
    '" tel: ' + ISNULL(i.TELEFONO,'—'),
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_CLIENTE = i.ID_CLIENTE;
END
GO

IF OBJECT_ID('dbo.TR_CLIENTES_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CLIENTES_DELETE;
GO
CREATE TRIGGER dbo.TR_CLIENTES_DELETE ON dbo.CLIENTES AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CLIENTES', 'DELETE',
    'Cliente eliminado: ' + NOMBRE + ' ' + APELLIDO,
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: C — ROLES ---- */

IF OBJECT_ID('dbo.TR_ROLES_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_ROLES_INSERT;
GO
CREATE TRIGGER dbo.TR_ROLES_INSERT ON dbo.ROLES AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'ROLES', 'INSERT',
    'Nuevo rol: "' + NOMBRE + '"',
    SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_ROLES_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_ROLES_UPDATE;
GO
CREATE TRIGGER dbo.TR_ROLES_UPDATE ON dbo.ROLES AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'ROLES', 'UPDATE',
    'Rol "' + d.NOMBRE + '" → nombre: "' + i.NOMBRE + '" estado: ' + i.ESTADO,
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_ROL = i.ID_ROL;
END
GO

IF OBJECT_ID('dbo.TR_ROLES_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_ROLES_DELETE;
GO
CREATE TRIGGER dbo.TR_ROLES_DELETE ON dbo.ROLES AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'ROLES', 'DELETE',
    'Rol eliminado: "' + NOMBRE + '"',
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: C — USUARIOS ---- */

IF OBJECT_ID('dbo.TR_USUARIOS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_USUARIOS_INSERT;
GO
CREATE TRIGGER dbo.TR_USUARIOS_INSERT ON dbo.USUARIOS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'USUARIOS', 'INSERT',
    'Nuevo usuario: ' + i.NOMBRE + ' ' + i.APELLIDO +
    ' usuario: "' + i.USUARIO + '" rol: "' + ISNULL(r.NOMBRE,'?') + '"',
    SYSTEM_USER
  FROM inserted i
  LEFT JOIN ROLES r ON i.ID_ROL = r.ID_ROL;
END
GO

IF OBJECT_ID('dbo.TR_USUARIOS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_USUARIOS_UPDATE;
GO
CREATE TRIGGER dbo.TR_USUARIOS_UPDATE ON dbo.USUARIOS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'USUARIOS', 'UPDATE',
    'Usuario "' + d.USUARIO + '" (' + d.NOMBRE + ' ' + d.APELLIDO + ')' +
    ' → estado: ' + i.ESTADO + ' rol: "' + ISNULL(r.NOMBRE,'?') + '"',
    SYSTEM_USER
  FROM deleted d
  JOIN inserted i ON d.ID_USUARIO = i.ID_USUARIO
  LEFT JOIN ROLES r ON i.ID_ROL = r.ID_ROL;
END
GO

IF OBJECT_ID('dbo.TR_USUARIOS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_USUARIOS_DELETE;
GO
CREATE TRIGGER dbo.TR_USUARIOS_DELETE ON dbo.USUARIOS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'USUARIOS', 'DELETE',
    'Usuario eliminado: ' + NOMBRE + ' ' + APELLIDO + ' ("' + USUARIO + '")',
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: J — RESERVAS ---- */

IF OBJECT_ID('dbo.TR_RESERVAS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_RESERVAS_INSERT;
GO
CREATE TRIGGER dbo.TR_RESERVAS_INSERT ON dbo.RESERVAS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'RESERVAS', 'INSERT',
    'Nueva reserva: cliente "' + ISNULL(c.NOMBRE+' '+c.APELLIDO,'?') +
    '" servicio "' + ISNULL(s.NOMBRE,'?') +
    '" fecha: ' + CONVERT(VARCHAR,i.FECHA_RESERVA,23) +
    ' hora: ' + CONVERT(VARCHAR,i.HORA_RESERVA,8) +
    ' estado: ' + i.ESTADO,
    SYSTEM_USER
  FROM inserted i
  LEFT JOIN CLIENTES  c ON i.ID_CLIENTE  = c.ID_CLIENTE
  LEFT JOIN SERVICIOS s ON i.ID_SERVICIO = s.ID_SERVICIO;
END
GO

IF OBJECT_ID('dbo.TR_RESERVAS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_RESERVAS_UPDATE;
GO
CREATE TRIGGER dbo.TR_RESERVAS_UPDATE ON dbo.RESERVAS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'RESERVAS', 'UPDATE',
    'Reserva cliente "' + ISNULL(c.NOMBRE+' '+c.APELLIDO,'?') +
    '" servicio "' + ISNULL(s.NOMBRE,'?') +
    '" fecha: ' + CONVERT(VARCHAR,i.FECHA_RESERVA,23) +
    ' | estado: ' + d.ESTADO + ' → ' + i.ESTADO,
    SYSTEM_USER
  FROM deleted d
  JOIN inserted i ON d.ID_RESERVA = i.ID_RESERVA
  LEFT JOIN CLIENTES  c ON i.ID_CLIENTE  = c.ID_CLIENTE
  LEFT JOIN SERVICIOS s ON i.ID_SERVICIO = s.ID_SERVICIO;
END
GO

IF OBJECT_ID('dbo.TR_RESERVAS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_RESERVAS_DELETE;
GO
CREATE TRIGGER dbo.TR_RESERVAS_DELETE ON dbo.RESERVAS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'RESERVAS', 'DELETE',
    'Reserva eliminada: cliente "' + ISNULL(c.NOMBRE+' '+c.APELLIDO,'?') +
    '" servicio "' + ISNULL(s.NOMBRE,'?') +
    '" fecha: ' + CONVERT(VARCHAR,d.FECHA_RESERVA,23),
    SYSTEM_USER
  FROM deleted d
  LEFT JOIN CLIENTES  c ON d.ID_CLIENTE  = c.ID_CLIENTE
  LEFT JOIN SERVICIOS s ON d.ID_SERVICIO = s.ID_SERVICIO;
END
GO

/* ---- RESPONSABLE: J — TRABAJOS ---- */

IF OBJECT_ID('dbo.TR_TRABAJOS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_TRABAJOS_INSERT;
GO
CREATE TRIGGER dbo.TR_TRABAJOS_INSERT ON dbo.TRABAJOS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'TRABAJOS', 'INSERT',
    'Nuevo trabajo: servicio "' + ISNULL(s.NOMBRE,'?') +
    '" atendido por "' + ISNULL(u.NOMBRE+' '+u.APELLIDO,'?') +
    '" precio cobrado: Bs.' + CAST(i.PRECIO_COBRADO AS VARCHAR) +
    ' estado: ' + i.ESTADO,
    SYSTEM_USER
  FROM inserted i
  LEFT JOIN SERVICIOS s ON i.ID_SERVICIO = s.ID_SERVICIO
  LEFT JOIN USUARIOS  u ON i.ID_USUARIO  = u.ID_USUARIO;
END
GO

IF OBJECT_ID('dbo.TR_TRABAJOS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_TRABAJOS_UPDATE;
GO
CREATE TRIGGER dbo.TR_TRABAJOS_UPDATE ON dbo.TRABAJOS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'TRABAJOS', 'UPDATE',
    'Trabajo servicio "' + ISNULL(s.NOMBRE,'?') +
    '" | estado: ' + d.ESTADO + ' → ' + i.ESTADO +
    ' precio: Bs.' + CAST(i.PRECIO_COBRADO AS VARCHAR),
    SYSTEM_USER
  FROM deleted d
  JOIN inserted i ON d.ID_TRABAJO = i.ID_TRABAJO
  LEFT JOIN SERVICIOS s ON i.ID_SERVICIO = s.ID_SERVICIO;
END
GO

IF OBJECT_ID('dbo.TR_TRABAJOS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_TRABAJOS_DELETE;
GO
CREATE TRIGGER dbo.TR_TRABAJOS_DELETE ON dbo.TRABAJOS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'TRABAJOS', 'DELETE',
    'Trabajo eliminado: servicio "' + ISNULL(s.NOMBRE,'?') +
    '" precio: Bs.' + CAST(d.PRECIO_COBRADO AS VARCHAR),
    SYSTEM_USER
  FROM deleted d
  LEFT JOIN SERVICIOS s ON d.ID_SERVICIO = s.ID_SERVICIO;
END
GO

/* ---- RESPONSABLE: J — PAGOS ---- */

IF OBJECT_ID('dbo.TR_PAGOS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_PAGOS_INSERT;
GO
CREATE TRIGGER dbo.TR_PAGOS_INSERT ON dbo.PAGOS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'PAGOS', 'INSERT',
    'Nuevo pago: cliente "' + ISNULL(c.NOMBRE+' '+c.APELLIDO,'?') +
    '" servicio "' + ISNULL(s.NOMBRE,'?') +
    '" monto: Bs.' + CAST(i.MONTO AS VARCHAR) +
    ' método: ' + i.METODO_PAGO +
    ' estado: ' + i.ESTADO,
    SYSTEM_USER
  FROM inserted i
  LEFT JOIN TRABAJOS t  ON i.ID_TRABAJO  = t.ID_TRABAJO
  LEFT JOIN RESERVAS r  ON t.ID_RESERVA  = r.ID_RESERVA
  LEFT JOIN CLIENTES c  ON r.ID_CLIENTE  = c.ID_CLIENTE
  LEFT JOIN SERVICIOS s ON r.ID_SERVICIO = s.ID_SERVICIO;
END
GO

IF OBJECT_ID('dbo.TR_PAGOS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_PAGOS_UPDATE;
GO
CREATE TRIGGER dbo.TR_PAGOS_UPDATE ON dbo.PAGOS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'PAGOS', 'UPDATE',
    'Pago cliente "' + ISNULL(c.NOMBRE+' '+c.APELLIDO,'?') +
    '" | monto: Bs.' + CAST(d.MONTO AS VARCHAR) + ' → Bs.' + CAST(i.MONTO AS VARCHAR) +
    ' estado: ' + d.ESTADO + ' → ' + i.ESTADO,
    SYSTEM_USER
  FROM deleted d
  JOIN inserted i ON d.ID_PAGO = i.ID_PAGO
  LEFT JOIN TRABAJOS t  ON i.ID_TRABAJO  = t.ID_TRABAJO
  LEFT JOIN RESERVAS r  ON t.ID_RESERVA  = r.ID_RESERVA
  LEFT JOIN CLIENTES c  ON r.ID_CLIENTE  = c.ID_CLIENTE;
END
GO

IF OBJECT_ID('dbo.TR_PAGOS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_PAGOS_DELETE;
GO
CREATE TRIGGER dbo.TR_PAGOS_DELETE ON dbo.PAGOS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'PAGOS', 'DELETE',
    'Pago eliminado: monto Bs.' + CAST(MONTO AS VARCHAR) +
    ' método: ' + METODO_PAGO,
    SYSTEM_USER
  FROM deleted;
END
GO

PRINT '✅ Triggers con nombres aplicados correctamente.';
