USE [DB_TiendaBelleza];
GO

/* ================================================================
   TRIGGERS — escriben en BITACORA
   Regla: GO debe estar en su propia línea
================================================================ */

/* ---- RESPONSABLE: CH — CATEGORIAS ---- */

IF OBJECT_ID('dbo.TR_CATEGORIAS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CATEGORIAS_INSERT;
GO
CREATE TRIGGER dbo.TR_CATEGORIAS_INSERT ON dbo.CATEGORIAS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CATEGORIAS', 'INSERT', 'Nueva categoría: ' + NOMBRE, SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_CATEGORIAS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CATEGORIAS_UPDATE;
GO
CREATE TRIGGER dbo.TR_CATEGORIAS_UPDATE ON dbo.CATEGORIAS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CATEGORIAS', 'UPDATE',
    'Categoría id=' + CAST(d.ID_CATEGORIA AS VARCHAR) +
    ' | Antes: ' + d.NOMBRE + ' → Después: ' + i.NOMBRE,
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_CATEGORIA = i.ID_CATEGORIA;
END
GO

IF OBJECT_ID('dbo.TR_CATEGORIAS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CATEGORIAS_DELETE;
GO
CREATE TRIGGER dbo.TR_CATEGORIAS_DELETE ON dbo.CATEGORIAS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CATEGORIAS', 'DELETE',
    'Categoría eliminada: ' + NOMBRE + ' (id=' + CAST(ID_CATEGORIA AS VARCHAR) + ')',
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: CH — SERVICIOS ---- */

IF OBJECT_ID('dbo.TR_SERVICIOS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_SERVICIOS_INSERT;
GO
CREATE TRIGGER dbo.TR_SERVICIOS_INSERT ON dbo.SERVICIOS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'SERVICIOS', 'INSERT',
    'Nuevo servicio: ' + NOMBRE + ' precio=' + CAST(PRECIO AS VARCHAR),
    SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_SERVICIOS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_SERVICIOS_UPDATE;
GO
CREATE TRIGGER dbo.TR_SERVICIOS_UPDATE ON dbo.SERVICIOS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'SERVICIOS', 'UPDATE',
    'Servicio id=' + CAST(d.ID_SERVICIO AS VARCHAR) +
    ' | Antes: ' + d.NOMBRE + ' $' + CAST(d.PRECIO AS VARCHAR) +
    ' → Después: ' + i.NOMBRE + ' $' + CAST(i.PRECIO AS VARCHAR),
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_SERVICIO = i.ID_SERVICIO;
END
GO

IF OBJECT_ID('dbo.TR_SERVICIOS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_SERVICIOS_DELETE;
GO
CREATE TRIGGER dbo.TR_SERVICIOS_DELETE ON dbo.SERVICIOS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'SERVICIOS', 'DELETE',
    'Servicio eliminado: ' + NOMBRE + ' (id=' + CAST(ID_SERVICIO AS VARCHAR) + ')',
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: P — CLIENTES ---- */

IF OBJECT_ID('dbo.TR_CLIENTES_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CLIENTES_INSERT;
GO
CREATE TRIGGER dbo.TR_CLIENTES_INSERT ON dbo.CLIENTES AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CLIENTES', 'INSERT', 'Nuevo cliente: ' + NOMBRE + ' ' + APELLIDO, SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_CLIENTES_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CLIENTES_UPDATE;
GO
CREATE TRIGGER dbo.TR_CLIENTES_UPDATE ON dbo.CLIENTES AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CLIENTES', 'UPDATE',
    'Cliente id=' + CAST(d.ID_CLIENTE AS VARCHAR) +
    ' | Antes: ' + d.NOMBRE + ' ' + d.APELLIDO +
    ' → Después: ' + i.NOMBRE + ' ' + i.APELLIDO,
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_CLIENTE = i.ID_CLIENTE;
END
GO

IF OBJECT_ID('dbo.TR_CLIENTES_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_CLIENTES_DELETE;
GO
CREATE TRIGGER dbo.TR_CLIENTES_DELETE ON dbo.CLIENTES AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'CLIENTES', 'DELETE',
    'Cliente eliminado: ' + NOMBRE + ' ' + APELLIDO,
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: C — ROLES ---- */

IF OBJECT_ID('dbo.TR_ROLES_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_ROLES_INSERT;
GO
CREATE TRIGGER dbo.TR_ROLES_INSERT ON dbo.ROLES AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'ROLES', 'INSERT', 'Nuevo rol: ' + NOMBRE, SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_ROLES_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_ROLES_UPDATE;
GO
CREATE TRIGGER dbo.TR_ROLES_UPDATE ON dbo.ROLES AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'ROLES', 'UPDATE',
    'Rol id=' + CAST(d.ID_ROL AS VARCHAR) +
    ' | Antes: ' + d.NOMBRE + ' → Después: ' + i.NOMBRE,
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_ROL = i.ID_ROL;
END
GO

IF OBJECT_ID('dbo.TR_ROLES_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_ROLES_DELETE;
GO
CREATE TRIGGER dbo.TR_ROLES_DELETE ON dbo.ROLES AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'ROLES', 'DELETE', 'Rol eliminado: ' + NOMBRE, SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: C — USUARIOS ---- */

IF OBJECT_ID('dbo.TR_USUARIOS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_USUARIOS_INSERT;
GO
CREATE TRIGGER dbo.TR_USUARIOS_INSERT ON dbo.USUARIOS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'USUARIOS', 'INSERT',
    'Nuevo usuario: ' + USUARIO + ' (' + NOMBRE + ' ' + APELLIDO + ')',
    SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_USUARIOS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_USUARIOS_UPDATE;
GO
CREATE TRIGGER dbo.TR_USUARIOS_UPDATE ON dbo.USUARIOS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'USUARIOS', 'UPDATE',
    'Usuario id=' + CAST(d.ID_USUARIO AS VARCHAR) +
    ' | Antes: ' + d.USUARIO + ' estado=' + d.ESTADO +
    ' → Después: ' + i.USUARIO + ' estado=' + i.ESTADO,
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_USUARIO = i.ID_USUARIO;
END
GO

IF OBJECT_ID('dbo.TR_USUARIOS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_USUARIOS_DELETE;
GO
CREATE TRIGGER dbo.TR_USUARIOS_DELETE ON dbo.USUARIOS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'USUARIOS', 'DELETE',
    'Usuario eliminado: ' + USUARIO + ' (id=' + CAST(ID_USUARIO AS VARCHAR) + ')',
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: J — RESERVAS ---- */

IF OBJECT_ID('dbo.TR_RESERVAS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_RESERVAS_INSERT;
GO
CREATE TRIGGER dbo.TR_RESERVAS_INSERT ON dbo.RESERVAS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'RESERVAS', 'INSERT',
    'Nueva reserva id=' + CAST(ID_RESERVA AS VARCHAR) +
    ' fecha=' + CONVERT(VARCHAR, FECHA_RESERVA, 23) + ' estado=' + ESTADO,
    SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_RESERVAS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_RESERVAS_UPDATE;
GO
CREATE TRIGGER dbo.TR_RESERVAS_UPDATE ON dbo.RESERVAS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'RESERVAS', 'UPDATE',
    'Reserva id=' + CAST(d.ID_RESERVA AS VARCHAR) +
    ' | Antes: estado=' + d.ESTADO + ' → Después: estado=' + i.ESTADO,
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_RESERVA = i.ID_RESERVA;
END
GO

IF OBJECT_ID('dbo.TR_RESERVAS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_RESERVAS_DELETE;
GO
CREATE TRIGGER dbo.TR_RESERVAS_DELETE ON dbo.RESERVAS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'RESERVAS', 'DELETE',
    'Reserva eliminada id=' + CAST(ID_RESERVA AS VARCHAR),
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: J — TRABAJOS ---- */

IF OBJECT_ID('dbo.TR_TRABAJOS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_TRABAJOS_INSERT;
GO
CREATE TRIGGER dbo.TR_TRABAJOS_INSERT ON dbo.TRABAJOS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'TRABAJOS', 'INSERT',
    'Nuevo trabajo id=' + CAST(ID_TRABAJO AS VARCHAR) +
    ' reserva=' + CAST(ID_RESERVA AS VARCHAR) +
    ' precio=' + CAST(PRECIO_COBRADO AS VARCHAR),
    SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_TRABAJOS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_TRABAJOS_UPDATE;
GO
CREATE TRIGGER dbo.TR_TRABAJOS_UPDATE ON dbo.TRABAJOS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'TRABAJOS', 'UPDATE',
    'Trabajo id=' + CAST(d.ID_TRABAJO AS VARCHAR) +
    ' | Antes: estado=' + d.ESTADO +
    ' → Después: estado=' + i.ESTADO,
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_TRABAJO = i.ID_TRABAJO;
END
GO

IF OBJECT_ID('dbo.TR_TRABAJOS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_TRABAJOS_DELETE;
GO
CREATE TRIGGER dbo.TR_TRABAJOS_DELETE ON dbo.TRABAJOS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'TRABAJOS', 'DELETE',
    'Trabajo eliminado id=' + CAST(ID_TRABAJO AS VARCHAR),
    SYSTEM_USER
  FROM deleted;
END
GO

/* ---- RESPONSABLE: J — PAGOS ---- */

IF OBJECT_ID('dbo.TR_PAGOS_INSERT','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_PAGOS_INSERT;
GO
CREATE TRIGGER dbo.TR_PAGOS_INSERT ON dbo.PAGOS AFTER INSERT AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'PAGOS', 'INSERT',
    'Nuevo pago id=' + CAST(ID_PAGO AS VARCHAR) +
    ' monto=' + CAST(MONTO AS VARCHAR) + ' metodo=' + METODO_PAGO,
    SYSTEM_USER
  FROM inserted;
END
GO

IF OBJECT_ID('dbo.TR_PAGOS_UPDATE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_PAGOS_UPDATE;
GO
CREATE TRIGGER dbo.TR_PAGOS_UPDATE ON dbo.PAGOS AFTER UPDATE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'PAGOS', 'UPDATE',
    'Pago id=' + CAST(d.ID_PAGO AS VARCHAR) +
    ' | Antes: monto=' + CAST(d.MONTO AS VARCHAR) + ' estado=' + d.ESTADO +
    ' → Después: monto=' + CAST(i.MONTO AS VARCHAR) + ' estado=' + i.ESTADO,
    SYSTEM_USER
  FROM deleted d JOIN inserted i ON d.ID_PAGO = i.ID_PAGO;
END
GO

IF OBJECT_ID('dbo.TR_PAGOS_DELETE','TR') IS NOT NULL
    DROP TRIGGER dbo.TR_PAGOS_DELETE;
GO
CREATE TRIGGER dbo.TR_PAGOS_DELETE ON dbo.PAGOS AFTER DELETE AS
BEGIN
  INSERT INTO BITACORA (TABLA, ACCION, DESCRIPCION, USUARIO_SISTEMA)
  SELECT 'PAGOS', 'DELETE',
    'Pago eliminado id=' + CAST(ID_PAGO AS VARCHAR) +
    ' monto=' + CAST(MONTO AS VARCHAR),
    SYSTEM_USER
  FROM deleted;
END
GO

PRINT '✅ Triggers aplicados correctamente.';
